version: "3.8"
services:
  db:
    image: postgres:17.0-alpine
    container_name: db_learningplatform
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 30s
      retries: 5

  migrator:
    image: golang:1.23-alpine
    container_name: migrator_learningplatform
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: ["/bin/sh", "./migrate.sh"]

volumes:
  db_data:
    name: pg_data_learningplatform