grpc_server:
  address: ":8002"
  timeout: "2s"
storage:
  type: "postgres"
  host: "localhost"
  port: 5435
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
rabbit_mq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  share_exchange:
    name: share
    kind: direct
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false
    args:
      alternate_exchange: alternate_exchange_share
  channel:
    channel_queue:
      name: channel
      durable: true
      auto_deleted: false
      exclusive: false
      no_wait: false
      # args:
      #   x_message_ttl: 600000
    channel_consumer:
      queue: channel
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5
    channel_routing_key: channel
  plan:
    plan_queue:
      name: plan
      durable: true
      auto_deleted: false
      exclusive: false
      no_wait: false
      # args:
      #   x_message_ttl: 600000
    plan_routing_key: plan
    plan_consumer:
      queue: plan
      consumer: ""
      autoAck: false
      exclusive: false
      noLocal: false
      noWait: false
      args:
        x-consumer-timeout: 60000
        x-consumer-prefetch-count: 5